export const URLS = {
    HOME_PAGE: "/",
    ABOUT_PAGE: "/about",
    CONTACT_PAGE: "/contact",
    MEASURE: "/measure",
    AUTHEN: "/my-account",
    MEN:'/list/men/page-1',
    MEN2:'/list/men/page-2',
    MEN3:'/list/men/page-3',
    WEDDING:'/list/wedding/page-1',
    ACCESSORIES:'/list/accessories/page-1',
    COAT:'/list/men/coat',
    SUITS:'/list/men/suits/page-1',
    SUITS2:'/list/men/suits/page-2',
    SHIRTS:'/list/men/shirts/page-1',
    SHIRTS2:'/list/men/shirts/page-2',
    BLAZERS:'/list/men/balzers',
    PANTS:'/list/men/pants',
    TAILORED:'/list/wedding/tailored',
    BRIDE:'/list/wedding/bride',
    BRIDES_MAID:'/list/wedding/brides-maid',
    TIES:'/list/accessories/ties',
    BOW_TIES:'/list/accessories/bow-ties',
    PAYMENT:'/payment',
    PAYMENT_DETAILS:'/payment-details',
    WISH_LIST:'/wish-list',

};
