export const CONTEXT_ACTION = {
  GET_ACTION: "CA_GET_ACCESS_TOKEN",
  SET_ACTION: "CA_SET_ACCESS_TOKEN",
};
export const BROADCAST_MESSAGE = {
  NEED_TOKEN: "BM_NEED_TOKEN",
  SEND_TOKEN: "BM_SEND_TOKEN",
  NEED_LOGOUT: "BM_NEED_LOGOUT",
};
export const TOKEN_EXPIRY_DAYS = {
  NON_REMEMBER: 24,
  REMEMBER: 24,
};
export const QUERY_KEYS = {
  VALIDATE_TOKEN: "QUERY_VALIDATE_TOKEN",
  GET_ACCOUNT_INFO: "QUERY_GET_ACCOUNT_INFO",
  GET_USER: "QUERY_GET_USER",
};
export const BROADCAST_CHANNEL = {
  AUTH_CHANNEL: "BC_AUTHENTICATION",
};
export const GOOGLE_MESSAGE = {
  LOGIN_SUCCESS: "GM_LOGIN_SUCCESS",
  LOGIN_FAILED: "GM_LOGIN_FAILED",
};
export const FACEBOOK_MESSAGE = {
  LOGIN_SUCCESS: "FM_LOGIN_SUCCESS",
  LOGIN_FAILED: "FM_LOGIN_FAILED",
};
