export const LOCAL_STORAGE_KEYS = {
  WISHLIST: "WISHLIST",
  IS_REMEMBER: "LOCAL_IS_REMEMBER",
  IS_POPUP_OPEN: "LOCAL_IS_POPUP_OPEN",
  CART_ADDRESS: "LOCAL_STORAGE_KEY_CART_ADDRESS",
  ORDER: "LOCAL_STORAGE_KEY_ORDER",
};
export const SESSION_STORAGE_KEY = {
  ACCESS_TOKEN: "SESSION_ACCESS_TOKEN",
};
export const COOKIE_KEY = {
  ACCESS_TOKEN: "COOKIE_ACCESS_TOKEN",
};
